<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            ['id' => 3, 'name' => 'Salim', 'email' => 'giacoman_salim@hotmail.com', 'password' => bcrypt('machinrin')],
            ['id' => 4, 'name' => 'Karla', 'email' => 'monsek_27@hotmail.com', 'password' => bcrypt('monserrat123')],
            ['id' => 8, 'name' => 'Usuario de Pruebas', 'email' => 'pruebas@pruebas.com', 'password' => bcrypt('Admin')],
            ['id' => 9, 'name' => 'Gerardo', 'email' => 'mmdmi@prodigy.net.mx', 'password' => bcrypt('Admin')],
            ['id' => 10, 'name' => 'Fernanda', 'email' => 'fernandatrejo123@hotmail.com', 'password' => bcrypt('fer123')],
            ['id' => 11, 'name' => 'Gilberto', 'email' => 'gilbertoviramontes@hotmail.com', 'password' => bcrypt('gilberto197545')],
            ['id' => 12, 'name' => 'German', 'email' => 'transportemartha@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 13, 'name' => 'Martin', 'email' => 'martin.triana@yahoo.com', 'password' => bcrypt('Admin')],
            ['id' => 14, 'name' => 'Luis Solares', 'email' => 'luissolaresf@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 15, 'name' => 'Alejandra Alvarado', 'email' => 'alealvaradoc3@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 16, 'name' => 'Angélica Reza', 'email' => 'probioser@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 17, 'name' => 'Veronica Perez', 'email' => 'veronica.c3casas@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 18, 'name' => 'Ana Maria Valdez', 'email' => 'anitavaldez_2012@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 20, 'name' => 'Lizeth Gomez', 'email' => 'lizz_yo04@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 21, 'name' => 'Bernardo', 'email' => 'bernardogomezporras@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 22, 'name' => 'Andres Ochoa', 'email' => 'almacentorreon@biotecap.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 23, 'name' => 'Alicia Ind. Borrego', 'email' => 'alicia.industrialborrego@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 24, 'name' => 'Elsa M. Valenzuela', 'email' => 'elsa_ale79@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 25, 'name' => 'Rosy Rayma', 'email' => 'rayma@siica.net', 'password' => bcrypt('Admin')],
            ['id' => 26, 'name' => 'Veronica Provetsso', 'email' => 'provetsso2010@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 27, 'name' => 'Juan Andres Tadeo Saenz Rodriguez', 'email' => 'andres.saenz@strategicbc.com.mx', 'password' => bcrypt('andres2310')],
            ['id' => 29, 'name' => 'Espacio de Desarrollo', 'email' => 'kindergymtorreon@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 30, 'name' => 'Nora Gonzalez', 'email' => 'ngonzalez@irsamexico.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 31, 'name' => 'Jorge Carreon', 'email' => 'proveedoradeagroquimicos@live.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 34, 'name' => 'Alejandro Sosa', 'email' => 'alexsosas@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 35, 'name' => 'Martin Esquivel', 'email' => 'mferesquivel@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 36, 'name' => 'Salvador Jaquez', 'email' => 'chava@mundotablaroca.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 37, 'name' => 'Margarita Zamora', 'email' => 'taxiaereo@chilchota.com', 'password' => bcrypt('Admin')],
            ['id' => 38, 'name' => 'Aide Trujillo', 'email' => 'aidebella@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 39, 'name' => 'Mary Bañuelos', 'email' => 'maryc3casas@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 40, 'name' => 'Sofia de la Torre', 'email' => 'sofia_delatorre@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 41, 'name' => 'Maquinados de Durango', 'email' => 'maquinados@mail.com', 'password' => bcrypt('Admin')],
            ['id' => 42, 'name' => 'Garfi Gas', 'email' => 'garfigas@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 43, 'name' => 'Dr. Jose Batarse', 'email' => 'josebatarse@yahoo.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 44, 'name' => 'Teatro Nazas', 'email' => 'admon_teatronazas@yahoo.com', 'password' => bcrypt('Admin')],
            ['id' => 45, 'name' => 'Farolitos', 'email' => 'farolitos.vi@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 46, 'name' => 'Martha Angelica', 'email' => 'disvetmar_2009@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 47, 'name' => 'CAVI', 'email' => 'cavi_torreon@yahoo.com', 'password' => bcrypt('Admin')],
            ['id' => 49, 'name' => 'Diseño Corporativo', 'email' => 'catr8@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 50, 'name' => 'Inmobilliaria Villa Jardín', 'email' => 'inmobiliariavillajardin@gmail.com', 'password' => bcrypt('Adminplazas')],
            ['id' => 51, 'name' => 'Jonathan Cepeda', 'email' => 'jonathancepeda66@hotmail.com', 'password' => bcrypt('Admin69')],
            ['id' => 53, 'name' => 'Cecilia Mena', 'email' => 'prointe15@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 54, 'name' => 'Blanca Estela', 'email' => 'blanca.t.m@live.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 55, 'name' => 'Jesus Rivas', 'email' => 'jesus.rivasgarcia@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 56, 'name' => 'Maria Ornelas', 'email' => 'maria.ornelas@medikercpm.com', 'password' => bcrypt('Admin')],
            ['id' => 57, 'name' => 'Mario Banderas', 'email' => 'deportes_marios@yahoo.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 58, 'name' => 'Grupo ARMUR', 'email' => 'facturacion@armur.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 59, 'name' => 'Despacho', 'email' => 'maof_s03@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 60, 'name' => 'Magnum', 'email' => 'magnum_carwash@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 62, 'name' => 'Raymundo E Urbano', 'email' => 'urbanosanchez80@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 63, 'name' => 'Ignacio', 'email' => 'ignaciomoran67@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 64, 'name' => 'America', 'email' => 'modemontes1@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 65, 'name' => 'Luis', 'email' => 'pachecolh@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 66, 'name' => 'Gabriela Flores', 'email' => 'contrerasulloaja@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 67, 'name' => 'Juancho', 'email' => 'juancho_72@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 68, 'name' => 'Miguel', 'email' => 'miguelwongrdz@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 70, 'name' => 'Alejandra', 'email' => 'aleurby@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 71, 'name' => 'Pizarro', 'email' => 'pizarro.04@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 72, 'name' => 'Enrique', 'email' => 'enriquecuba@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 73, 'name' => 'Juan Jose', 'email' => 'juanjosepadilla@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 74, 'name' => 'Teresa Gaytan', 'email' => 'teresuchi_21@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 75, 'name' => 'Enrique Cordova', 'email' => 'ecordovau1@gmail.com','password' => bcrypt('Admin')],
            ['id' => 76, 'name' => 'Alan Castro', 'email' => 'castrobussines@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 77, 'name' => 'Icom', 'email' => 'icomtradesol@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 78, 'name' => 'Enrique Lopez', 'email' => 'elopez_53@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 79, 'name' => 'Juan Carlos', 'email' => 'juanc_echevarrieta@yahoo.co', 'password' => bcrypt('Admin')],
            ['id' => 80, 'name' => 'Rocio de Anda', 'email' => 'rociodeandadecuadros@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 81, 'name' => 'Olga De la Torre', 'email' => 'roman2521@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 82, 'name' => 'Tony Silva', 'email' => 'argmexsi@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 83, 'name' => 'Sergio Aguiñaga', 'email' => 'sagacom2004@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 84, 'name' => 'Lupita', 'email' => 'lu_iisa07@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 85, 'name' => 'Isela Acosta', 'email' => 'acosta.isel@hotmail.com', 'password' => bcrypt('Is3l4')],
            ['id' => 86, 'name' => 'Sucursal Garfigas Chihuahua', 'email' => 'garfigas1@mail.com', 'password' => bcrypt('Admin')],
            ['id' => 88, 'name' => 'rodima', 'email' => 'rodimadelnorte@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 89, 'name' => 'Salim Antonio', 'email' => 'sagmah@msn.com', 'password' => bcrypt('shalom')],
            ['id' => 91, 'name' => 'Alejandro del Valle', 'email' => 'advalle@siica.net', 'password' => bcrypt('Admin')],
            ['id' => 92, 'name' => 'Jesús Favela Limón', 'email' => 'jesus_favela_limon@yahoo.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 94, 'name' => 'Lizeth Gómez Féliz', 'email' => 'lizeth.gomez@strategicbc.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 95, 'name' => 'Lupita Gómez Féliz', 'email' => 'lupita.gomez@strategicbc.com.mx', 'password' => bcrypt('Admin1')],
            ['id' => 96, 'name' => 'Mirna Moncayo', 'email' => 'mirna.moncayo@strategicbc.com.mx', 'password' => bcrypt('Admin1')],
            ['id' => 97, 'name' => 'Itza Pájaro', 'email' => 'itza.pajaro@strategicbc.com.mx', 'password' => bcrypt('Admin1')],
            ['id' => 99, 'name' => 'Gabriel Diaz Gonzalez', 'email' => 'gabriel.gonzalez@strategicbc.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 100, 'name' => 'Oscar Gonzalez', 'email' => 'lugo_adm01@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 101, 'name' => 'Jaime H. Ramirez Delgado', 'email' => 'jaimehonorato@outlook.es', 'password' => bcrypt('Admin')],
            ['id' => 102, 'name' => 'Carlos Gonzalez', 'email' => 'cgonzalez@siica.net', 'password' => bcrypt('Admin')],
            ['id' => 103, 'name' => 'ROCIO PEREZ', 'email' => 'cemalag16@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 104, 'name' => 'Oscar Daniel Cabrales Pineda', 'email' => 'holadesierto@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 105, 'name' => 'Iveth Muñoz', 'email' => 'iveth.gtcservicios@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 106, 'name' => 'Nemesio Romero Acevedo', 'email' => 'nemeromero@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 107, 'name' => 'Saul Rodríguez', 'email' => 'saul@mundotablaroca.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 109, 'name' => 'Pedro Gil Torres', 'email' => 'mariaisabel@mail.com', 'password' => bcrypt('Admin')],
            ['id' => 111, 'name' => 'Alicia Piña', 'email' => 'facturas@esfera.com', 'password' => bcrypt('Admin')],
            ['id' => 114, 'name' => 'Limisa', 'email' => 'limisa_fiscal@hotmail.com', 'password' => bcrypt('LIMISA2018')],
            ['id' => 115, 'name' => 'salim', 'email' => 'giacoman_salim@gmail.com', 'password' => bcrypt('PRU3Qpe3')],
            ['id' => 116, 'name' => 'Manuel Gamboa García', 'email' => 'manuelcrece@gmail.com', 'password' => bcrypt('725036')],
            ['id' => 117, 'name' => 'Nelly Girón', 'email' => 'nelly.giron@strategicbc.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 118, 'name' => 'Carmen Cano', 'email' => 'posada_delrey@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 119, 'name' => 'Miguel Diaz', 'email' => 'mkl59@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 120, 'name' => 'Pedro Gil Torres', 'email' => 'reparaciones.morales12@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 121, 'name' => 'Izahac Ramirez', 'email' => 'zejoz@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 122, 'name' => 'Arely Urbano', 'email' => 'arely.urbano@dhmining.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 123, 'name' => 'Jorge Sanchez', 'email' => 'jeduardoss@ligamayor.com.mx', 'password' => bcrypt('Admin')],
            ['id' => 124, 'name' => 'Saultane', 'email' => 'tane@xx.com	Saultane', 'password' => bcrypt('123456')],
            ['id' => 125, 'name' => 'Ivonne Diaz', 'email' => 'automarcasmarcos@hotmail.com', 'password' => bcrypt('Maba1010@')],
            ['id' => 126, 'name' => 'Jose Alvarado', 'email' => 'josealvaradovilla@yahoo.com', 'password' => bcrypt('Admin')],
            ['id' => 127, 'name' => 'Lupita Gomez', 'email' => 'contabilidad02@grupostr.mx', 'password' => bcrypt('Admin')],
            ['id' => 128, 'name' => 'VIELMA Y ACOSTA', 'email' => 'vielmayacosta@prodigy.net.mx', 'password' => bcrypt('vielsa01')],
            ['id' => 129, 'name' => 'Belem Sanchez', 'email' => 'facturasc10@hotmail.com', 'password' => bcrypt('Dátiles#24')],
            ['id' => 130, 'name' => 'Roberto Romero Ruiz', 'email' => 'maq_indromero@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 131, 'name' => 'Leydi Osmara R Chuc', 'email' => 'osmara.roc@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 132, 'name' => 'Mantenimiento del Sistema Mi Factura Fiscal', 'email' => 'operaciones@grupostr.mx', 'password' => bcrypt('Admin2')],
            ['id' => 133, 'name' => 'Federico Ehrenzweig Hernandez', 'email' => 'fedesin@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 134, 'name' => 'Juancho el del Rancho', 'email' => 'juancho_ag72@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 135, 'name' => 'Raul Ibarra', 'email' => 'raul.ibarra71@yahoo.com', 'password' => bcrypt('Str15')],
            ['id' => 136, 'name' => 'Miguel Hidalgo', 'email' => 'chef.miguel.hidalgo@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 137, 'name' => 'MARIA GUADALUPE TORRES', 'email' => 'maquinadostorres22@gmail.com', 'password' => bcrypt('Admin')],
            ['id' => 138, 'name' => 'Gustavo Armendariz', 'email' => 'gustavo.armendariz@kinglong.mx', 'password' => bcrypt('User1')],
            ['id' => 139, 'name' => 'Naye', 'email' => 'naye.arz88@hotmail.com', 'password' => bcrypt('Admin')],
            ['id' => 140, 'name' => 'Alejandro del Vale', 'email' => 'alejandro.valle@grupostr.com', 'password' => bcrypt('K6!82z@&$')],
            ['id' => 141, 'name' => 'KRISTIAN ANDRES CONTRERAS FLORES', 'email' => 'kcfcontreras@hotmail.com', 'password' => bcrypt('Cofk980824')],
            ['id' => 142, 'name' => 'Itza', 'email' => 'contabilidad04@grupostr.mx', 'password' => bcrypt('123Itza123')],
            ['id' => 143, 'name' => 'vicentehernandez', 'email' => 'vhernandezgomez55@gmail', 'password' => bcrypt('0FH05$GmhL')],
            ['id' => 144, 'name' => 'Juana Prueba', 'email' => 'juanaprueba@hotmail.com', 'password' => bcrypt('HolaHolaa')],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }
    }
}
